name: Building new Clang

# on:
#   push:
#     branches:
#       - clang/*
#   schedule:
#     - cron: '15 1 * * *'

env:
  GITLAB_NAME: ${{ secrets.GITLAB_NAME }}
  GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GIT_SECRET: ${{ secrets.GIT_SECRET }}

jobs:
  TigaLebas:

    runs-on: ubuntu-20.04

    container: 
      image: zycromerz/tcdocker:v1

    steps:
    - uses: actions/checkout@v2
    - name: Build TC
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export PATH=/usr/bin/core_perl:$PATH
        bash ci.sh deps
        bash update-clang-version.sh
        bash clang-builder.sh 13 gi

  EmpatLebas:

    runs-on: ubuntu-20.04

    container: 
      image: zycromerz/tcdocker:v1

    steps:
    - uses: actions/checkout@v2
    - name: Build TC
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export PATH=/usr/bin/core_perl:$PATH
        bash ci.sh deps
        bash update-clang-version.sh
        bash clang-builder.sh 14 gi
